### ISSUE TITLE
Unable to push the application to Cloud

### ISSUE THREAD

**Issue by sangy05** [IBM-Swift/Kitura-WebSocket#82]
I can build the package successfully on my mac using swift 4.2.1. However, when i try to push to bluemix, its gets hanged at Fetching https://github.com/IBM-Swift/OpenSSL.git . Also, I noticed that the packages that are fetched are different for mac and IBM cloud. Could be due to Linux. But no clue how to proceed.

**Comment by ddunn2** [comment]
@sangy05  Thanks for raising an issue! 
We will take a look into recreating your issue now and get back to you when we have more information. 

In the meantime could you provide the contents of your Package.swift file?

Thanks again!

**Comment by sangy05** [comment]
@ddunn2 : Sure david, here is the package content.

// swift-tools-version:4.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SocketServer",
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura.git", from: "2.6.1"),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMinor(from: "1.7.0")),
        .package(url: "https://github.com/IBM-Swift/Kitura-WebSocket.git", from: "2.1.1")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "SocketServer",
            dependencies: ["Kitura", "HeliumLogger", "Kitura-WebSocket"])
    ]
)

**Comment by ddunn2** [comment]
Thanks @sangy05 

The issue is with this line in your Package.swift: 
`.package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMinor(from: "1.7.0")),`

Kitura 2.3 onwards requires HeliumLogger at version 1.8 or above. 

A solution to your issue would be to update the line in your Package.swift to pull in the correct version of HeliumLogger:
`.package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: "1.8.0"),`

If there is a reason you need HeliumLogger at version 1.7 please let me know and I'll help guide you through this.

I hope this helps!

**Comment by sangy05** [comment]
Excellent!! It worked. Thanks.. But I just wonder how the same didn't fail when I run in the local. ?
